on:
  workflow_call:
    inputs:
      docker-name:
        description: The full name of your DockerHub repository, e.g. "my-docker-name/my-repo-name"
        required: true
        type: string
      docker-username:
        description: Your DockerHub username
        required: true
        type: string
      kube-deployment:
        description: The name of your Kubernetes Deployment resource to update with your latest image tag
        required: true
        type: string
    secrets:
      docker-password:
        description: A Dockerhub Access Token with permissions to upload your container to Dockerhub
        required: true
      kube-config:
        description: A base64 encded string of your Kubernetes cluster's config file
        required: true

env:
  DOCKER_TAG: "${{ inputs.docker-name }}:${{ github.sha }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
      with:
        ruby-version: '2.7'
    - name: Install dependencies
      run: bundle install
    - name: Build Jekyll site
      run: bundle exec jekyll build
    - name: Build the Docker image
      run: docker build . --tag "$DOCKER_TAG"
    - name: Login to Docker
      run: echo "${{ secrets.docker-password }}" | docker login -u "${{ inputs.docker-username }}" --password-stdin
    - name: Make this Docker image tag the latest
      run: docker tag "$DOCKER_TAG" "${{ inputs.docker-name }}:latest"
    - name: Push Docker image
      run: docker image push --all-tags "${{ inputs.docker-name }}"
  publish:
    environment: Production
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.kube-config }}
    - name: Update Kubernetes deployment
      run: kubectl set image "deployment/${{ inputs.kube-deployment }}" "main=$DOCKER_TAG"